name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      # 현재 레포지토리 코드 업로드
      - name: Checkout my code
        uses: actions/checkout@v3

      # JAVA JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 유닛 테스트
      - name: Run Unit Test
        run:
          ./gradlew test

  build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: unittest

    steps:
      # 현재 레포지토리 업로드
      - name: Checkout my code
        uses: actions/checkout@v3

      # JAVA JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      # Spring 빌드
      - name: Spring Build, Make .jar
        run:
          ./gradlew build

      # Docker 설정
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v2

      # Docker 빌드
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Image meta 설정
      - name: Set up Docker Image meta data
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: baesa/baesa

      # Docker Hub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Build, Docker Hub Push
      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    # 배포는 추후 작성
    steps:
      # 현재 레포지토리 업로드
      - name: Checkout my code
        uses: actions/checkout@v3

      # 정상적으로 clone 되었는지 확인
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al